<template>
    <HomeTron></HomeTron>
    <HomeDestination></HomeDestination>
    <HomePackage></HomePackage>
    <HomeCallActionPromo></HomeCallActionPromo>
    <HomePromo></HomePromo>
    <HomeGallery></HomeGallery>
    <HomeCallActionOffer></HomeCallActionOffer>
    <HomeTestimonial></HomeTestimonial>
    <HomeCallAction></HomeCallAction>
</template>